version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://weather_user:password@db:5432/weatherdb
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weatherdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
