"""Remove weather_stats table

Revision ID: 92cbc328b09c
Revises: e1ab3ceaafdf
Create Date: 2025-01-26 20:52:59.612615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92cbc328b09c"
down_revision: Union[str, None] = "e1ab3ceaafdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_stats")

    op.execute(
        """
    CREATE VIEW weather_stats_view AS
    SELECT
        station_id,
        EXTRACT(YEAR FROM date) AS year,
        AVG(max_temp) AS avg_max_temp,
        AVG(min_temp) AS avg_min_temp,
        SUM(precipitation) AS total_precipitation
    FROM
        weather_data
    WHERE
        max_temp != -9999 AND
        min_temp != -9999 AND
        precipitation != -9999
    GROUP BY
        station_id, EXTRACT(YEAR FROM date);
    """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_stats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("station_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "avg_max_temp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_min_temp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_precipitation",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="weather_stats_pkey"),
        sa.UniqueConstraint("station_id", "year", name="uq_weatherstats_station_year"),
    )

    op.execute("DROP VIEW IF EXISTS weather_stats_view;")
    # ### end Alembic commands ###
